# Generated by Django 5.2.13 on 2026-08-17 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_ats_safe', models.BooleanField(default=True)),
                ('preview_image', models.CharField(blank=True, default='', max_length=255)),
                ('html_path', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('company', models.CharField(blank=True, default='', max_length=255)),
                ('raw_text', models.TextField()),
                ('extracted_keywords', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_descriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_master', models.BooleanField(default=False)),
                ('template_id', models.IntegerField(default=1)),
                ('target_job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('target_company', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tailored_resumes', to='resumes.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('tech_stack', models.JSONField(blank=True, default=list)),
                ('link', models.URLField(blank=True, default='', max_length=255)),
                ('bullets', models.JSONField(blank=True, default=list)),
                ('order_index', models.IntegerField(default=0)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='resumes.resume')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('linkedin_url', models.URLField(blank=True, default='', max_length=255)),
                ('github_url', models.URLField(blank=True, default='', max_length=255)),
                ('portfolio_url', models.URLField(blank=True, default='', max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to='resumes.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('start_date', models.CharField(blank=True, default='', max_length=50)),
                ('end_date', models.CharField(blank=True, default='', max_length=50)),
                ('is_current', models.BooleanField(default=False)),
                ('raw_description', models.TextField(blank=True, default='')),
                ('bullets', models.JSONField(blank=True, default=list)),
                ('order_index', models.IntegerField(default=0)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='resumes.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('field_of_study', models.CharField(blank=True, default='', max_length=255)),
                ('start_date', models.CharField(blank=True, default='', max_length=50)),
                ('end_date', models.CharField(blank=True, default='', max_length=50)),
                ('grade', models.CharField(blank=True, default='', max_length=50)),
                ('order_index', models.IntegerField(default=0)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='resumes.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('issuer', models.CharField(blank=True, default='', max_length=255)),
                ('issue_date', models.CharField(blank=True, default='', max_length=50)),
                ('credential_url', models.URLField(blank=True, default='', max_length=255)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='resumes.resume')),
            ],
        ),
        migrations.CreateModel(
            name='ATSAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(default=0.0)),
                ('keyword_match_score', models.FloatField(default=0.0)),
                ('skills_match_score', models.FloatField(default=0.0)),
                ('job_title_match_score', models.FloatField(default=0.0)),
                ('experience_relevance_score', models.FloatField(default=0.0)),
                ('education_score', models.FloatField(default=0.0)),
                ('structure_score', models.FloatField(default=0.0)),
                ('formatting_score', models.FloatField(default=0.0)),
                ('matched_keywords', models.JSONField(blank=True, default=list)),
                ('missing_keywords', models.JSONField(blank=True, default=list)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ats_analyses', to='resumes.jobdescription')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ats_analyses', to='resumes.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Technical', max_length=100)),
                ('skill_name', models.CharField(max_length=255)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='resumes.resume')),
            ],
        ),
    ]
