# Generated by Django 6.1 on 2026-08-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
